common/scala/src/main/scala/org/apache/openwhisk/core/database/ActivationStore.scala, common/scala/src/main/scala/org/apache/openwhisk/core/database/ArtifactActivationStore.scala
This PR removes the check for the store activations limit from class _ActivationStore_. Reason is that by implementing the switch here not only storing the activations is disabled, but also the logdna support for user logs is omitted which isn't intended by setting this limit. 
The check for store activations limit will moved to the _ArtifactActivationStore_ class where the activation store is implemented
=> Don't evaluate limit to not store activations for limitted namespaces in ActivationStore class

tools/jenkins/apache/dockerhub.groovy
Push nightly images to ibmfunctions org on docker hub.
Modifications to adapt tools/jenkins/apache/dockerhub.groovy to push nightly images to ibmfunctions org on docker hub.
These nightly images are e.g. used by the functions runtimes in ibm-functions org at github.com.
=> Push nightly images to ibmfunctions org on docker hub.

tests/src/test/scala/org/apache/openwhisk/core/database/ArtifactWithFileStorageActivationStoreTests.scala
In our tests we encounter every now and then failing tests that fail because `Futures timed out after 10 seconds` (java.util.concurrent.TimeoutException).
This code change increases the timeout value from 10 to 30 seconds. Intention is to avoid the following error for awaiting results in `ArtifactWithFileStorageActivationStoreTests` class: `java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]`
=> Increase maximum wait time value to omit intermittent timeout exceptions

tools/jenkins/apache/dockerhub.groovy
Add PD alerting to dockerhub.groovy.
Add sending PD alerts when the build fails. Reset a possible pending alert once the build is ok again.
=> Add PD alerting to dockerhub.groovy.

tests/src/test/scala/org/apache/openwhisk/core/database/test/DatabaseScriptTestUtils.scala, tests/src/test/scala/org/apache/openwhisk/core/database/test/ExtendedCouchDbRestClient.scala
In our tests we encounter every now and then failing tests that fail because `412 Precondition Failed (details: {"error":"file_exists","reason":"The database could not be created, the file already exists."}`.
This code change checks in addition that a delete database request gets really effective before continuing to create the same database. Intention is to avoid the following error when creating a database: `org.scalatest.exceptions.TestFailedException: Left(412 Precondition Failed (details: {"error":"file_exists","reason":"The database could not be created, the file already exists."}))`
=> Make sure database is deleted in tests to avoid error on create

tests/src/test/scala/system/basic/WskPackageTests.scala
In our tests we encounter every now and then failing tests that fail because of timeouts or other reasons.
=> Retry for all WskPackageTests to stabilize mainBluewhisk build

tests/src/test/scala/system/basic/WskActionTests.scala
In our tests we encounter every now and then failing tests that fail because of timeouts or other reasons.
=> Retry for all WskActionTests to stabilize mainBluewhisk

common/scala/Dockerfile
Upgrade openjdk to address PSIRT issues for java/scala based components
=> Upgrade Openjdk to jdk8u252-b09_openj9-0.20.0

common/scala/src/main/scala/org/apache/openwhisk/common/TransactionId.scala, common/scala/src/main/scala/org/apache/openwhisk/core/database/FileStorage.scala, common/scala/src/main/scala/org/apache/openwhisk/core/entity/ActivityEvent.scala, common/scala/src/main/scala/org/apache/openwhisk/http/ActivityTracker.scala, common/scala/src/main/scala/org/apache/openwhisk/http/BasicHttpService.scala, core/controller/src/main/scala/org/apache/openwhisk/core/controller/BasicAuthenticationDirective.scala, core/controller/src/main/scala/org/apache/openwhisk/core/controller/Controller.scala, core/controller/src/main/scala/org/apache/openwhisk/core/controller/Rules.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActivityTrackerTests.scala
This PR adds audit logging to track activities on the Controller API based on the CADF (Cloud Auditing Data Federation) standard DSP0262, v1.0.0.
**Please note: an additional log rotation for the created activity tracker audit logs needs to be installed (basically the same as for user logs.) Otherwise, the file system runs full.**
The implementation plugs in the BasicHttpService. A request handler collects information from incoming http requests, the authenticaton components BasicAuthenticationDirective and IAMAuthenticationDirective collect some additional information dependent on the authentication type, and the response handler adds some more information and finally creates the related activity events and stores them as audit log in the file system.
The request handler and the …
=> Add activity tracker audit logs

core/controller/src/main/scala/org/apache/openwhisk/core/controller/WebActions.scala
Support Functions `appdomain.cloud` for Web Actions, reverse check for filtering domain, we now enable filtering if request is not initiated from our white-listed appdomain.cloud domain
=> Support Functions appdomain.cloud for Web Actions - Reverse check for filtering domain

tests/src/test/scala/org/apache/openwhisk/core/database/test/DbUtils.scala
In our tests we encounter every now and then failing tests that fail because of `java.util.concurrent.TimeoutException: Futures timed out after [15 seconds]`
This code change increases the timeout (dbOpTimeout) value from 15 to 30 seconds. Intention is to avoid the following error for awaiting results in eg `org.apache.openwhisk.core.controller.test.ActionsApiWithDbPollingTests` class: `java.util.concurrent.TimeoutException: Futures timed out after [15 seconds]`
=> Increase timeout for awaiting DB results in DbUtils from 15 to 30 seconds

common/scala/src/main/scala/org/apache/openwhisk/common/TransactionId.scala, common/scala/src/main/scala/org/apache/openwhisk/core/database/FileStorage.scala, common/scala/src/main/scala/org/apache/openwhisk/core/entity/ActivityEvent.scala, common/scala/src/main/scala/org/apache/openwhisk/http/ActivityTracker.scala, core/controller/src/main/scala/org/apache/openwhisk/core/controller/ApiUtils.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActivityTrackerTests.scala
This PR adds code to activate activity tracker events for enable/diable rule api calls. A previous PR https://github.com/ibm-functions/openwhisk/pull/18 already added code to handle these calls. But that PR did not activate the controller to also handle activity events. As a consequence, no events were created for enable/diable rule api calls since POST calls are not handled by the crudcontroller.
Furthermore, this PR adds update events. Code is added that determines whether a PUT operation is a create or an update operation. Accordingly, create or update events are created.
The activity tracker is now enabled for the controller, too. This is required to handle the http POST calls to the rules API for enabling or disabling rules. Summary of changes by file:
- `TransactionId`: a new tag …
=> Activate activity tracker events for enable/diable rule and add update events

tests/src/test/scala/org/apache/openwhisk/core/database/UserCommandTests.scala
=> Retry for all UserCommandTests to stabilize mainBluewhisk

tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ArtifactStoreQueryBehaviors.scala
```
16:00:20  org.apache.openwhisk.core.database.CouchDBArtifactStoreTests > CouchDBArtifactStore query should find single entity STANDARD_OUT
16:00:20      [2020-06-30T10:00:20.206Z] [INFO] SessionTrackerImpl exited loop!
16:00:21      [2020-06-30T14:00:19.859Z] [INFO] [#tid_sid_unknown] [WhiskConfig] reading properties from file /home/cusina/workspace/mainWhisk/blue/whisk.properties
16:00:21      [2020-06-30T14:00:19.860Z] [DEBUG] [#tid_sid_unknown] [WhiskConfig] properties file set value for …
```
=> Retry for all CouchDBArtifactStore to stabilize mainBluewhisk

tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActivationsApiTests.scala
```
01:00:13  org.apache.openwhisk.core.controller.test.ActivationsApiTests > Activations API should skip activations and return correct ones STANDARD_OUT
01:00:13      condition not met, retrying
01:00:13      condition not met, retrying
01:00:13      condition not met, retrying
01:00:13      condition not met, retrying
01:00:13      condition not met, retrying
01:00:13      condition not met, retrying
01:00:13      condition not met, retrying
01:00:13      condition not met, retrying
01:00:13 …
```
=> Retry on failures for all ActivationsApiTests to stabilize mainBluewhisk

tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ArtifactStoreAttachmentBehaviors.scala
```
17:11:37  org.apache.openwhisk.core.database.CouchDBArtifactStoreTests > CouchDBArtifactStore attachments should put and read large attachment STANDARD_OUT
17:11:37      [2020-07-02T15:11:31.753Z] [INFO] [#tid_47] [WhiskAction] write initiated on new cache entry
17:11:37      [2020-07-02T15:11:31.755Z] [INFO] [#tid_47] [CouchDbRestStore] [PUT] 'fn-dev-build_whisks' saving document: 'id: artifactTCK_Fft8_ns_CqjPQ/attachment_large, rev: null' [marker:database_saveDocument_start:540]
17:11:37 …
```
=> Retry on failures for all ArtifactStoreAttachmentBehaviors to stabilize mainBluewhisk

tests/src/test/scala/org/apache/openwhisk/core/cli/test/ApiGwRestBasicTests.scala, tests/src/test/scala/org/apache/openwhisk/core/cli/test/BaseApiGwTests.scala
This code change tries to recover from one of these intermittent failures by retrying the failed test. Objective is to stabilize the `mainBluewhisk` builds.
```
21:09:20      Starting test Wsk api should verify get API name that uses custom package at 2020-07-03 15:09:17.702
21:09:20  
21:09:20  org.apache.openwhisk.core.cli.test.ApiGwRestTests > Wsk api should verify get API name that uses custom package STANDARD_OUT
21:09:20      Action invokes within last minute: 28
21:09:20      Action invokes within last minute: 28
21:09:20      Action invokes within last minute: 27
21:09:20  
21:09:20  org.apache.openwhisk.core.cli.test.ApiGwRestTests > Wsk api …
```
=> Make package deletion success required, check if package was deleted afterwards

tests/src/test/scala/org/apache/openwhisk/core/controller/test/TriggersApiTests.scala
```
18:30:16  org.apache.openwhisk.core.controller.test.TriggersApiTests > Triggers API should list triggers by default/explicit namespace STANDARD_OUT
18:30:16      condition not met, retrying
18:30:16      condition not met, retrying
18:30:16      condition not met, retrying
18:30:16      condition not met, retrying
18:30:16  
18:30:16  org.apache.openwhisk.core.controller.test.TriggersApiTests > Triggers API should list triggers by default/explicit namespace FAILED
18:30:16 …
```
=> Retry on failures for all TriggersApiTests to stabilize mainBluewhisk

tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ActivationStoreQueryBehaviors.scala
```
14:41:02  org.apache.openwhisk.core.database.ArtifactActivationStoreTests > ArtifactActivationStore listActivationsMatchingName should support limiting results STANDARD_OUT
14:41:02      [2020-07-05T12:40:38.893Z] [DEBUG] [#tid_AO8L5yB0PNpNm4NRS9x89x1Zd7bX7Sk1] [ArtifactActivationStore] recording activation 'f7a16c73837c476ba16c73837cb76b02'
14:41:02      [2020-07-05T12:40:38.893Z] [INFO] [#tid_AO8L5yB0PNpNm4NRS9x89x1Zd7bX7Sk1] [CouchDbRestStore] [PUT] 'fn-dev-build_activations' saving document: 'id: …
```
=> Retry on failures for all ActivationStoreQueryBehaviors tests to stabilize mainBluewhisk

tests/src/test/scala/org/apache/openwhisk/core/controller/test/BasicAuthenticateTests.scala
```
20:36:13  org.apache.openwhisk.core.controller.test.BasicAuthenticateTests > Authenticate should authorize a known user using different namespaces and cache key, and reject invalid secret STANDARD_OUT
20:36:13      condition not met, retrying
20:36:13  
20:36:13  org.apache.openwhisk.core.controller.test.BasicAuthenticateTests > Authenticate should authorize a known user using different namespaces and cache key, and reject invalid secret FAILED
20:36:13      java.util.NoSuchElementException: None.get …
```
=> Retry on failures for all BasicAuthenticateTests tests to stabilize mainBluewhisk

common/scala/src/main/scala/org/apache/openwhisk/core/database/CouchDbRestStore.scala, tests/src/test/scala/common/WskTestHelpers.scala
This code change tries to recover from one of these intermittent failures by retrying the failed test. Objective is to stabilize the `mainBluewhisk` builds.
The PR add the error details to the `DocumentConflictException` if 409 errors occur for CouchDB delete requests. It also does retries in the AssetCleaner logic for 409 errors for all asset types/operations.
```
org.apache.openwhisk.core.cli.test.ApiGwRestTests > Wsk api should verify get API name that uses custom package STANDARD_OUT
Action invokes within last minute: 0
Action invokes within last minute: 1
Action invokes within last minute: 2
exit code = 153
stdout: …
```
=> Provide details on DocumentConflictException for CouchDB and do retries in AssetCleaner on 409 for all operations 

tests/src/test/scala/system/basic/WskRuleTests.scala
```
00:34:43      Starting test Whisk rules should disable a rule and check its status is displayed when listed at 2020-07-08 18:34:43.027
00:34:47  
00:34:47  system.basic.WskRestRuleTests > Whisk rules should disable a rule and check its status is displayed when listed STANDARD_OUT
00:34:47      Exception occurred during test execution: org.scalatest.exceptions.TestFailedException: false was not equal to true
00:34:47  
00:34:47  system.basic.WskRestRuleTests > Whisk rules should disable a rule and …
```
=> Retry on failures for all WskRuleTests tests to stabilize mainBluewhisk

common/scala/src/main/scala/org/apache/openwhisk/http/ErrorResponse.scala, core/controller/src/main/scala/org/apache/openwhisk/core/controller/WebActions.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/WebActionsApiTests.scala
Provide the activation id in response error payload of web actions that time out
When invoking an action, there are two modes possible, blocking or non-blocking.
The default for regular action invocations is 'non-blocking', for web actions it is blocking.
Blocking invocations use a request-response style and wait for the activation result to be available.
The wait period is the lesser of 60 seconds or the action's timeout limit.
At the end of the wait period (i.e. after 60 sec), ALL invocations will switch to non-blocking and instead of the result they return the activation id such as
```
{
"activationId": "27eca80056d54f93aca80056d5cf93b9"
}
```
If an invocation of a web action reaches the end of wait period, the response will just show the transaction id and an indication that the …
=> Provide activation id in response error payload of web actions that time out

common/scala/src/main/scala/org/apache/openwhisk/core/entity/Identity.scala
Log first two characters of EK key in case passed identity cannot be found in identities view
We recently received a severity 1 ticket where the customer complained that his trigger didn't work anymore.
After some debugging we found out that the passed identity was no longer valid. 
In order to support the error analysis the code now logs also the first two characters of the EK key in case it cannot be found and the authentication fails.
=> Log first two characters of EK key in case of an error

ansible/roles/controller/tasks/deploy.yml, common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala, core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/InvokerSupervision.scala, core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
Disable invoker supervision for crudcontrollers
One reason for overloading invokers ( `rescheduling Run message, too many message in the pool`) is the fact that the crudcontrollers are also sending health actions to the invokers as the behave as regular controllers, which is NOT considered in the bookkeeping of the regular controllers. Usually this should not hurt, but in high load scenarios it could make the situation worse. For crudcontrollers this is not needed! .. and should be 'switched off' (based on discussion in [#whisk-teams](https://ibm-argonauts.slack.com/archives/GA651JS2F/p1601637587011200?thread_ts=1601478109.006700&cid=GA651JS2F))
With this PR the following changes are done:
- Define an additional controller environment property `controller.name` set to `controller` or …
=> Disable invoker supervision for crudcontrollers

core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerPool.scala
Log how much memory is still available on the chosen invoker per invocation
As we still see `rescheduling Run message, too many message in the pool` for no obvious reason this is to log more details to further analyze the situation.
=> Log how much memory is still available on the chosen invoker per invocation

core/controller/src/main/scala/org/apache/openwhisk/core/entitlement/ActivationThrottler.scala, core/controller/src/main/scala/org/apache/openwhisk/core/entitlement/Entitlement.scala, core/controller/src/main/scala/org/apache/openwhisk/core/entitlement/RateThrottler.scala, tests/src/test/scala/limits/ThrottleTests.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/RateThrottleTests.scala
Consider second controller for `Too many (concurrent) requests` messages.
Today the response provided by the API/CLI is misleading because it's indicating that e.g. the default limit of invocations per minute is 3000, which is actually not the case. The reason is that the limit is spread over/enforced by 2 controller in the cluster where each controller maintains the half + 10% overhead. For a limit of 5000 for invocations per minute this leads to (5000 + 20%)/#controller = 6000/2 = *3000*
The code change in this PR addresses this problem by taking the number (2) of controller in the cluster into account. As the number of requests handled by the other controller is not known by the controller that returns the error in case the limit is violated the count value in the error is still not …
=> Consider second controller for too many (concurrent) requests errors

tests/src/test/scala/org/apache/openwhisk/core/entity/test/SchemaTests.scala
Fix testcase to also accept `nodejs:12` as a nodejs default runtime, too.
The test `initialize exec manifest` did not accept `nodejs:12` as default runtime and failed in this case.
This change now modifies the test to also accept `nodejs:12` as the default nodejs runtime.
=> Fix testcase to also accept nodejs:12 as default.

core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
Consider always half the invoker slot capacity
Consider only half of the invoker slot capacity also if akka cluster is temporary fallen apart (split brain). Intention is to avoid that both controller work with the full invoker capacity in case of a split brain situation which leads to invoker overloads (rescheduling run messages).
=> Always calculate half of the capacity

common/scala/src/main/scala/org/apache/openwhisk/core/entity/ActivityEvent.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActivityTrackerTests.scala
AT logs to cover responses with status >= 400 on action/trigger POST
Failed action/trigger POSTs are logged now as `functions.action.activate` failures
=> [AT] AT logs to cover responses with status >= 400 on action/trigger POST 

tests/src/test/scala/common/WskTestHelpers.scala, tests/src/test/scala/org/apache/openwhisk/core/admin/WskAdminTests.scala
Make test for strings (`allowedKinds`) independent of existence of Python unicode literal (`u'`).
Test should work independent if the Python unicode literal does exists as part of the string or not.
=> Make WskAdminTests independent of python unicode literal

core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/NamespaceBlacklist.scala
Blacklist invoker controller pings using same means as blacklisting namespaces
Blacklist controller pings sent every second to to inform controllers about general availability/healthiness using same means as blacklisting namespaces
=> Disable controller pings by blacklisting invoker

common/scala/src/main/scala/org/apache/openwhisk/utils/Retry.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/PackagesApiTests.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/TriggersApiTests.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/migration/SequenceActionApiMigrationTests.scala, tests/src/test/scala/org/apache/openwhisk/core/entity/test/ViewTests.scala, tests/src/test/scala/system/basic/WskConductorTests.scala
```
15:18:28  system.basic.WskConductorTests > Whisk conductor actions should invoke a conductor action with a continuation STANDARD_OUT
15:18:28      Exception occurred during test execution: org.scalatest.exceptions.TestFailedException: The future returned an exception of type: akka.http.impl.engine.client.OutgoingConnectionBlueprint$UnexpectedConnectionClosureException, with message: The http server closed the connection …
```
=> Retry on testcase failures

tests/src/test/scala/common/WskTestHelpers.scala, tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskEntitlementTests.scala, tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskRestBasicUsageTests.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActivationsApiTests.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/PackagesApiTests.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/TriggersApiTests.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/migration/SequenceActionApiMigrationTests.scala, tests/src/test/scala/system/basic/WskConductorTests.scala, tests/src/test/scala/system/basic/WskRestBasicTests.scala
```
07:18:57      Starting test Wsk Action REST should create, update, get and list an action at 2021-03-22 02:18:56.850
07:18:58  
07:18:58  system.basic.WskRestBasicTests > Wsk Action REST should create, update, get and list an action STANDARD_OUT
07:18:58      Exception occurred during test execution: org.scalatest.exceptions.TestFailedException: false was not equal to true
07:18:58  
07:18:58  system.basic.WskRestBasicTests > …
```
=> Retry on testcase failures (cont.)

tests/src/test/scala/limits/ThrottleTests.scala, tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ActivationStoreQueryBehaviors.scala, tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ArtifactStoreAttachmentBehaviors.scala, tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ArtifactStoreQueryBehaviors.scala, tests/src/test/scala/org/apache/openwhisk/core/limits/ActionLimitsTests.scala, tests/src/test/scala/system/basic/WskActionTests.scala, tests/src/test/scala/system/basic/WskActivationTests.scala, tests/src/test/scala/system/basic/WskMultiRuntimeTests.scala, tests/src/test/scala/system/basic/WskPackageTests.scala, tests/src/test/scala/system/basic/WskRestRuleTests.scala, tests/src/test/scala/system/basic/WskRuleTests.scala, tests/src/test/scala/system/basic/WskUnicodeTests.scala
```
[2021-03-23T13:06:23.054Z] system.basic.WskRestRuleTests > Whisk rules should disable a rule and check its status is displayed when listed STANDARD_OUT
[2021-03-23T13:06:23.054Z]     assetsToDeleteAfterTest += common.rest.RestTriggerOperations@4fe4bb10,ruleDisableTrigger-1616504782518,true
[2021-03-23T13:06:23.510Z]     assetsToDeleteAfterTest += common.rest.RestActionOperations@47a7c9aa,ruleDisableAction-1616504782518,true …
```
=> Retries on testcase failures (cont.)

core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/InvokerSupervision.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
Log invoker info `invokerid/uniqueName/displayName` (eg `invoker2/10.208.32.124/invoker-cjtth`) in invoker and controller log.
Show full invoker info to easier identify offline/unhealthy invokers from the log.
=> Log full  invoker info

common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala, core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/InvokerSupervision.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
Blacklist invoker using same means as blacklisting namespaces
Blacklist invoker by adding the info if a certain invoker is being blacklisted to the ping message and consider this info in the invoker supervision logic (`FSM`) to transition the state of an invoker to offline if it blacklisted.
Just suppressing the ping messages sent every second by each invoker is not sufficient as in high load scenarios where constantly invocations are scheduled to an invoker the `StateTimeout` message is not not sent by Scala `FSM` as the the acknowledgment messages sent for the processed activations will cancel the timeout.
=> Add isBlacklisted flag to ping message

common/scala/src/main/scala/org/apache/openwhisk/core/entity/BasicAuthenticationAuthKey.scala, common/scala/src/main/scala/org/apache/openwhisk/core/entity/Identity.scala, core/controller/src/main/scala/org/apache/openwhisk/core/controller/BasicAuthenticationDirective.scala, core/controller/src/main/scala/org/apache/openwhisk/core/controller/RestAPIs.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/NamespaceBlacklist.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/BasicAuthenticateTests.scala
Blacklist on account level
This code change enables the blacklisting on account level. By doing so invokes on all namespaces of the blacklisted account will be rejected (`error: Unable to invoke action.. Too many requests in the last minute (count: 1, allowed: 0).`)
=> Blacklist on account level

core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/InvokerSupervision.scala
Blacklist invoker using same means as blacklisting namespaces
This is a continuation of the PR https://github.com/ibm-functions/openwhisk/pull/82
It corrects the Scala formatting of `InvokerSupervision.scala`
```
Execution failed for task ':core:controller:checkScalafmt'.
346> Files incorrectly formatted: /home/travis/build/BlueMix-Fabric/bluewhisk/open/core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/InvokerSupervision.scala
```
=> Add isBlacklisted flag to ping message (cont.)

tests/dat/actions/unicode.tests/src/dotnet2.2/Apache.OpenWhisk.UnicodeTests.Dotnet/Unicode.cs
Avoid file does not end with EOL error in `Unicode.cs`
This is to avoid the following error:
```
can detected 1 error(s) in 1 file(s):
704  [/home/travis/build/ibm-functions/openwhisk/tools/travis/../../tests/dat/actions/unicode.tests/src/dotnet2.2/Apache.OpenWhisk.UnicodeTests.Dotnet/Unicode.cs]:
705      35: file does not end with EOL.
706
707Scan detected 1 error(s) in 1 file(s):
708The command "./tools/travis/runUnitTests.sh" exited with 1.
```
=> Avoid file does not end with EOL error in Unicode.cs

common/scala/src/main/scala/org/apache/openwhisk/core/database/CouchDbRestClient.scala, tests/src/test/scala/org/apache/openwhisk/core/database/test/ExtendedCouchDbRestClient.scala
Make the usage of activations databases flexible.
This code change allows _Functions_ to not pin the activations database at deployment time, but instead use it on a daily base (e.g. ` fn-dev-build_activations-18827`). This allows a much better cleanup of old activations databases.
The new logic is controlled by the setting of the activations database name (`db.whisk.activations`) at deployment time. If the name does not end with suffix `activations-` the old behavior applies and the activations database as defined is used for storing and reading activation documents.
Activation documents are copied from one activations database to the next by Cloudant replication means, so if a new activations database is being used activation documents stored before in the previous database are also …
=> Make usage of activations db flexible

tests/src/test/scala/org/apache/openwhisk/core/database/test/ReplicatorTests.scala
Make sure that the replication doc was deleted
This code change checks if a certain replication document created in a testcase was really deleted in Cloudant and retries the delete if not. Currently most of the replication documents (e.g `backup_1619575874_replicatortest_wrongprefix_fn-dev-pg2_expired_backup_wrong_prefix` stay in the database forever.
```
Removing replication doc: backup_1627018780_replicatortest_wrongprefix_fn-dev-pg2_expired_backup_wrong_prefix
caught exception: Some(Right({"id":"backup_1627018780_replicatortest_wrongprefix_fn-dev-pg2_expired_backup_wrong_prefix","ok":true,"rev":"2-046d25e794983c3187bc408d3a209f19"})) was not equal to None
Removing replication doc: backup_1627018780_replicatortest_wrongprefix_fn-dev-pg2_expired_backup_wrong_prefix
caught exception: …
```
=> Make sure replication doc was deleted

tests/src/test/scala/org/apache/openwhisk/core/database/test/ReplicatorTests.scala
Make sure that the replication doc was deleted
This code change checks if a certain replication document created in a testcase was really deleted in Cloudant and retries the delete if not. Currently some of the replication documents (e.g `backup_1627265878_replicatortest_fn-dev-pg1_notexpired_backup` stay in the database forever.
=> Make sure replication doc was deleted (cont.)

core/controller/src/main/scala/org/apache/openwhisk/core/controller/RestAPIs.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/RespondWithHeadersTests.scala
Add Content-Security-Policy response header in controller RestAPI
- Dynamic App Scan complains about Cloud Functions RestApi not setting `Content-Security-Policy` security response header which can help to protect against cross-site scripting attacks.
- Adding the following header:
- `Content-Security-Policy: default-src 'none'; frame-ancestors 'none'`
- Impact to end-users cannot be estimated as we don't know their usage/integration pattern of our RestApi, but risk seems low.
- The change does not impact WebActions, only the RestAPI.
- Existing test cases are adjusted accordingly. Additionally, changes are verified via cURL and Functions CLI verbose output.
- n/a
=> Add Content-Security-Policy response header in controller RestAPI

gradle/docker.gradle
docker build should use the option --no-cache to ensure the image is always built.
Reason is, that docker build uses a cached image, when the dockerfile (and the base image) has not changed.
But our dockerfiles has commands like `apt get update` inside, that may pick up fixes and updates during build.
---
- [x ] I signed an [Apache CLA](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md).
- [x ] I reviewed the [style guides](https://github.com/apache/openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
=> Docker build nocache

core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
Check the file system disk space usage to avoid that invokers run out of space
Invoker pods may run out of space on their log volume for very frequent scheduled actions producing a high load of log messages. By this code change this situation is taken into consideration and the affected invoker will be temporary evacuated until the situation relaxes.
=> Check the file system disk space usage to avoid that invokers run out of space

common/scala/src/main/scala/org/apache/openwhisk/core/database/CouchDbRestClient.scala, common/scala/src/main/scala/org/apache/openwhisk/core/database/RemoteCacheInvalidation.scala, common/scala/src/main/scala/org/apache/openwhisk/http/PoolingRestClient.scala, core/controller/src/main/scala/org/apache/openwhisk/core/controller/Controller.scala
Controller cache invalidation
Current implementation invalidate caches between controllers on updating the cache on one of the controllers and informing the other controller in the same cluster about the change using Kafka.
This PR adds the ability to invalidate caches between controllers on different clusters using CouchDB. If configured controllers are polling the `/db/_changes` resource and based on the list of changes made to documents in the database updates its caches accordingly.
=> Controller cache invalidation

tests/performance/gatling_tests/src/gatling/scala/org/apache/openwhisk/BlockingInvokeOneActionSimulation.scala
Make duration for warm containers up configurable for Scala Gatling test `BlockingInvokeOneActionSimulation`
=> Make duration for warm containers up configurable

common/scala/src/main/scala/org/apache/openwhisk/core/database/CouchDbRestClient.scala, common/scala/src/main/scala/org/apache/openwhisk/core/database/CouchDbRestStore.scala
Make the usage of activations databases flexible.
This code change enables the controller and invoker to perform CRUD operations (read and update activation document) and view operations (list activations in namespace, list activations matching name in namespace and count activations in namespace) in two databases to ensure that activation documents are accessible for (at least) 24 hours after creation and thereby not relying on activations documents being replicated by means of Cloudant. The change is done within the data store layer. 
The code change was successfully tested using a fully qualified activations database (`PG6#564`), using a not fully qualified activations database but with disabled extended flexible activations database logic (`PG6#565`) and using a not fully qualified …
=> Make usage of activations db flexible (cont.)

common/scala/src/main/scala/org/apache/openwhisk/core/database/DocumentFactory.scala, common/scala/src/main/scala/org/apache/openwhisk/core/database/MultipleReadersSingleWriterCache.scala, common/scala/src/main/scala/org/apache/openwhisk/core/database/RemoteCacheInvalidation.scala, common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskAction.scala, common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskActivation.scala, common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskPackage.scala, common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskRule.scala, common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskTrigger.scala, tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskWebActionsTests.scala
Controller cache invalidation (cont.)
Current implementation invalidate caches between controllers on updating the cache on one of the controllers and informing the other controller in the same cluster about the change using Kafka.
This PR adds the ability to invalidate caches between controllers on different clusters using CouchDB. If configured controllers are polling the `/db/_changes` resource and based on the list of changes made to documents in the database updates its caches accordingly. This will be done only on the controller side. For the crudcontroller caching is bypassed if CouchDB based cache invalidation is active.
=> Controller cache invalidation (cont.)

common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala, core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/InvokerSupervision.scala, core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala, tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/InvokerSupervisionTests.scala, tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
Transport disk pressure info in ping protocol and extend `Offline` invoker state (if applicable) by substate, timestamp at which state changed and details about the disk space used in case of disk pressure.
For `Offline` invoker state the `varz` endpoint will show the following info depending on whether the invoker is disabled, has disk pressure or is offline because of other reasons (e.g. state timeout).
```
{"invoker2/10.x/invoker-xxxxx":"down"}
{"invoker2/10.x/invoker-xxxxx":"down/disabled(1648713488516)"}
{"invoker2/10.x/invoker-xxxxx":"down/diskpressure(43,91,1648713488516)"}
```
=> Consider disk pressure in ping protocol

tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/InvokerSupervisionTests.scala
This is to fix an incorrectly formatted Scala test file (InvokerSupervisionTests.scala``).
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':bluemix:tests:checkTestScalafmt'.
> Files incorrectly formatted: /home/travis/build/BlueMix-Fabric/bluewhisk/open/tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/InvokerSupervisionTests.scala
```
=> Correct Scala format error in test class

common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala
This is to fix an incorrectly formatted Scala file (`Message.scala`).
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':common:scala:checkScalafmt'.
> Files incorrectly formatted: /home/travis/build/BlueMix-Fabric/bluewhisk/open/common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala
```
=> Correct Scala format error in  class (cont.)

core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
This is to fix an incorrectly formatted Scala file (`ShardingContainerPoolBalancer.scala`).
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':core:controller:checkScalafmt'.
> Files incorrectly formatted: /home/travis/build/BlueMix-Fabric/bluewhisk/open/core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
```
=> Correct Scala format error in class (cont.)

core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala, tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
Consider always half the invoker slot capacity
Consider only half of the invoker slot capacity also if akka cluster is temporary fallen apart (split brain). Intention is to avoid that both controller work with the full invoker capacity in case of a split brain situation which leads to invoker overloads (rescheduling run messages).
=> Always calculate half of the capacity (cont.)

common/scala/src/main/scala/org/apache/openwhisk/core/database/CouchDbRestClient.scala, common/scala/src/main/scala/org/apache/openwhisk/core/database/RemoteCacheInvalidation.scala
Fix Scala compile deprecation warnings:
```
[2022-03-14T20:56:13.947Z] > Task :common:scala:compileScala
[2022-03-14T20:56:13.947Z] Pruning sources from previous analysis, due to incompatible CompileSetup.
[2022-03-14T20:56:37.826Z] /home/cusina/workspace/Playground2-Fyre/
open/common/scala/src/main/scala/org/apache/openwhisk/core/database/CouchDbRestClient.scala:31: 
Unused import
[2022-03-14T20:56:37.826Z] import org.apache.openwhisk.core.entity.UUIDs
[2022-03-14T20:56:37.826Z]                                         ^
[2022-03-14T20:57:11.270Z] /home/cusina/workspace/Playground2-Fyre/
open/common/scala/src/main/scala/org/apache/openwhisk/core/database/RemoteCacheInvalidation.scala:71: 
The outer reference in this type test cannot be checked at run time.
[2022-03-14T20:57:11.270Z] …
```
=> [Scala] Fix compile warnings

common/scala/Dockerfile, core/controller/Dockerfile, core/cosmosdb/cache-invalidator/Dockerfile, core/invoker/Dockerfile, core/monitoring/user-events/Dockerfile
Given AdoptOpenJDK is deprecated,
we want to move to IBM Semeru Runtime Open Edition OpenJ9 images.
=> change base image to ibm-semeru-runtimes:open-8u332-b09-jdk-focal

core/controller/src/main/scala/org/apache/openwhisk/core/controller/WebActions.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/WebActionsApiTests.scala
Consider always half the invoker slot capacity
This patch fixes a bug whereby webactions cannot respond to OPTIONS even for default CORS responses because the handler check for authentication first, before checking if the requests if an OPTIONS request.
Actions which respond to OPTIONS explicitly will be invoked even if not authenticated yet but this should be acceptable since the action cannot respond to OPTIONS otherwise.
=> Allow OPTIONS response on web actions before checking for authentication

core/controller/src/main/scala/org/apache/openwhisk/core/controller/Actions.scala, core/controller/src/main/scala/org/apache/openwhisk/core/controller/Packages.scala, core/controller/src/main/scala/org/apache/openwhisk/core/controller/Rules.scala, core/controller/src/main/scala/org/apache/openwhisk/core/controller/Triggers.scala
Revert validate PUT playload for unexpected fields to reject with `400 Bad Request` for Action/Package/Trigger/Rule create/update requests.
=> Revert validate PUT payload for unexpected fields

.gitignore, tests/dat/actions/build.sh, tests/dat/actions/unicode.tests/go-1.15.txt, tests/dat/actions/unicode.tests/go-1.17.txt, tests/dat/actions/unicode.tests/python-3.7.txt, tests/dat/actions/unicode.tests/python-3.9.txt, tests/dat/actions/unicode.tests/ruby-2.6.txt
- Also run the unicode tests for go:1.15, go:1.17, java, python:3.7, python:3.9 and ruby:2.6 runtime kinds.
Successful PG: PG6-614
Include additional template actions for the unicode test in order to also check the latest runtime kinds.
=> Run unicode tests for newer runtimes.

common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala, core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/InvokerSupervision.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerPool.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
Transport container pool info in ping protocol and extend `Offline` invoker state (if applicable) by substate, timestamp at which state changed and the number of scheduled activations (sum of busy containers and waiting messages) in case the invoker is disabled. This allows to programmatically determine if an invoker is free of work if it is disabled.
For `Offline` invoker state the `varz` endpoint will show the following info depending on whether the invoker is disabled, has disk pressure or is offline because of other reasons (e.g. state timeout).
```
{"invoker2/10.x/invoker-xxxxx":"down"}
{"invoker0/10.x/invoker-xxxxx":"down/disabled(running=19,rootfs=36%,logsfs=17%,time=1648713488516)"}
{"invoker2/10.x/invoker-xxxxx":"down/diskpressure(running=0,rootfs=91%,logsfs=43%,time=1648713488516 …
```
=> Consider busy pool size and waiting messages in ping protocol

core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
Log activation when read from Kafka.
Log activation when read from Kafka with `warn` log level.
=> Log activation when read from Kafka

tests/performance/gatling_tests/src/gatling/scala/org/apache/openwhisk/LatencySimulation.scala
- The Scala runtime is deprecated and is therefore removed from the performance tests.
- The Scala runtime is deprecated and is therefore removed from the performance tests.
=> Remove Scala runtime from performance tests.

core/controller/src/main/scala/org/apache/openwhisk/core/controller/Triggers.scala
Retry action activation post call in case of errors.
Retry action activation post call in case of errors. This is to recover from `TcpIdleTimeoutException` which shows up regularly but not very frequent in the logs and which indicates a race condition in Akka Http.
=> Retry action activation post call in case of errors

ansible/files/runtimes.json, tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala
- Disable/deprecate the swift runtime as it is currently not supported.
Swift versions > 4.2 always require a recompile of the whole source code inside the action container due to the dependency checker using filesystem inodes (they are different for each container created) to determine if rebuild is required. This makes the execution of swift actions taking very long. A possible work around is to manually compile the swift action into an amd64 binary executable and use this with the dockerskeleton.
=> Disable swift runtime.

tools/ow-utils/Dockerfile
- The updated semeru java runtime does not contain python-pip anymore. Therefore moving to python3-pip instead.
=> Update image ow-utils to python3-pip.

tests/src/test/scala/org/apache/openwhisk/core/database/test/ReplicatorTests.scala
Set source and target for replication documents to URL like values to avoid `local_endpoints_not_supported` error on creation.
Set source and target for replication documents to URL like values to avoid `local_endpoints_not_supported` error on creation . Cloudant seems to has changed behavior and does not allow anymore the creation of replication documents with empty source and target fields. Cloudant rejects the create in this case with error `forbidden', 'local_endpoints_not_supported'.`
=> Set source and target to url values to avoid local_endpoints_not_supported error

tests/dat/actions/unicode.tests/python-3.11.txt
Add python:3.11 to the unicode tests.
Add python:3.11 to the unicode tests.
=> Add python:3.11 to the unicode tests.

.github/workflows/run-tests.yml, tools/travis/runSystemTests.sh, tools/travis/runTests.sh
- Cleanup docker images at start to free disk space. Otherwise it can happen that the invokers do not allow action execution as the free disk space is less than 85% during the tests.
- Output the invoker and controller logs in case there was an error during test execution. Allows easier debugging.
- Cleanup docker images at start to free disk space. Otherwise it can happen that the invokers do not allow action execution as the free disk space is less than 85% during the tests.
=> Docker images cleanup at github action start.

core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
Check the file system disk space usage to avoid that invokers run out of space. Make the max threshold values for root and logs filesystem configurable.
Invoker pods may run out of space on their root and log volumes for very frequent scheduled actions producing a high load of log messages or because of many docker images which are not cleaned up. By this code change this situation is taken into consideration and the affected invoker will be temporary evacuated until the situation has been resolved. By this code change the file system occupation is checked every minute. Also the logic to do hysteresis has been removed as it interferes with the image monitor.
=> [Invoker] Check the file system disk space usage to avoid that invokers run out of space (cont.)

core/controller/src/main/scala/org/apache/openwhisk/core/controller/BasicAuthenticationDirective.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/NamespaceBlacklist.scala
Blacklist on account level
This code change enables the blacklisting on account level. By doing so invokes on all namespaces of the blacklisted account will be rejected (`error: Unable to invoke action.. Too many requests in the last minute (count: 1, allowed: 0).`)
=> Blacklist on account level (cont.)

common/scala/Dockerfile, tools/ow-utils/Dockerfile
- Update jdk parent image to ibm-semeru-runtimes:open-8u402-b06-jdk-focal to get latest vulnerability fixes.
- Update jdk parent image to ibm-semeru-runtimes:open-8u402-b06-jdk-focal to get latest vulnerability fixes.
- n/a
=> Update jdk parent image to tag 'open-8u402-b06-jdk-focal'.

core/invoker/init.sh
We observed a network refused problem in the prewarmed container, that are setup during invoker container startup.
Inserted a 30 second sleep before starting the invoker container. This gives other containers and the network more time to properly setup before the invoker starts and creates the prewarmed containers.
=> delay invoker container

core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/ImageMonitor.scala
Record all invoked docker images and related actions and put them in store. Make sure the couchdb view is updated accordingly. Filter out outdated images on initial sync with image store.
Record all invoked docker images and related actions and put them in store.
=> Image monitor (cont.)

ansible/roles/prereq/tasks/deploy.yml
Use python requests==2.31.0.
- The previously requested requests==2.10.0 did not met the docker==4.0.2 requirements. Because of this pip always installed the latest version of requests. This worked until requests==2.32.2 was installed. This version contained changes which made the docker package to fail with for example: "Error connecting: Error while fetching server API version: Not supported URL scheme http+docker". This caused the deployment step to fail the build.
Installing requests==2.31.0 now avoids that the install of docker==4.0.2 updates to the latest requests and makes the builds successful again.
=> Use python requests==2.31.0.

build.gradle, tools/travis/scan.sh
Fix Scala build errors because of broken dependency of `cz.alenkacz.gradle.scalafmt` by excluding scalafmt plugin.
```
+ ./gradlew :bluemix:tests:testHealthWithRouter -DtestResultsDirName=test-results-ys0 -Dtestthreads=2
Downloading https://services.gradle.org/distributions/gradle-5.5.1-all.zip
..................................................................................................................................
Unzipping /home/jenkins/.gradle/wrapper/dists/gradle-5.5.1-all/8yl0syll3fr5m1v472nzznadi/gradle-5.5.1-all.zip to /home/jenkins/.gradle/wrapper/dists/gradle-5.5.1-all/8yl0syll3fr5m1v472nzznadi
Set executable permissions for: /home/jenkins/.gradle/wrapper/dists/gradle-5.5.1-all/8yl0syll3fr5m1v472nzznadi/gradle-5.5.1/bin/gradle
Welcome to Gradle 5.5.1!
Here are the …
```
=> Remove dependency to cz.alenkacz.gradle.scalafmt
