ibm-functions/openwhisk

- tests/src/test/scala/limits/ThrottleTests.scala
> Retry for all ThrottleTests and NamespaceSpecificThrottleTests to stabilize mainBluewhisk build

- tests/src/test/scala/org/apache/openwhisk/core/limits/ActionLimitsTests.scala
In our tests we encounter every now and then failing tests that fail because of timeouts or other reasons.
> Retry for all ActionLimitsTests to stabilize mainBluewhisk build

- tests/src/test/scala/services/KafkaConnectorTests.scala
In our tests we encounter every now and then failing tests that fail because of timeouts or other reasons.
> Retry for all KafkaConnectorTests to stabilize mainBluewhisk

- core/controller/src/main/scala/org/apache/openwhisk/core/controller/WebActions.scala
- tests/dat/actions/echo-env.js
- tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskWebActionsTests.scala
Support Functions `appdomain.cloud` for Web Actions.
> Support Functions appdomain.cloud for Web Actions (part 1)

- ansible/files/genssl.sh
Adapt generation of certificates so that it can handle domain names >64 characters.
For domains >64 characters the creation of the certificates switches to provide the domain name in the `subjectAltName` section instead of the subject.
In the subject field, the length of CN field is limited to 64 characters. In the subjectAltName field, the CN can be up to 254 characters.
> Support domain names >64 characters.

- common/scala/Dockerfile
Command 'docker --host pg1-functions-ci.rtp.raleigh.ibm.com:4243 build -t scala /home/cusina/workspace/pg1/open/common/scala' failed with exitCode 3 :
```
Step 6/11 : RUN apk add --update sed curl bash && apk update && apk upgrade
11:05:23   ---> Running in fa4d6258a343
11:05:23  fetch https://alpine.global.ssl.fastly.net/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
11:05:23  [91m140160580746568:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913:
11:05:23  ERROR: https://alpine.global.ssl.fastly.net/alpine/v3.12/main: Permission denied
11:05:23  WARNING: Ignoring APKINDEX.a38da714.tar.gz: No such file or directory
```
The target server for `apk add` has updated to the latest certificates, that cannot be verified by the used …
> scala image Dockerfile - update ca-certificates

- tests/src/test/scala/org/apache/openwhisk/core/database/test/DatabaseScriptTestUtils.scala
> Handle eventual consistency problems when creating or deleting a database in Cloudant

- tests/src/test/scala/org/apache/openwhisk/core/database/test/DbUtils.scala
In order to cover a greater time interval with less retries make this parameter configurable. Again this is to handle Cloudant eventual consistency problems. It was pre-configured/fixed to 50 milliseconds before.
```
00:32:02      create fake costriggerfeed document with id Systemtest-Namespace-863941f8-74a0-41cd-a963-f16f674c00e0, namespace crn crn:v1:bluemix:public:functions:us-south:a/2f5e673290ade974bb748fe69ed77ded:8577d45b-f0e8-4fd8-9bf3-7d4b7514c927:: and trigger name 8577d45b-f0e8-4fd8-9bf3-7d4b7514c927/test-trigger-some-1 with retries...
00:32:02  
00:32:02      wait that costrigger document appears in view...
00:32:03      headOption returned empty option
00:32:03      condition not met, retrying
00:32:03      condition not met, retrying
00:32:03      condition not met, retrying …
```
> Make grace period in DbUtils retry method configurable

- tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskEntitlementTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskRestEntitlementTests.scala
> Check if test identity is visible in view before continue with tests to stabilize mainBluewhisk

- tests/src/test/scala/org/apache/openwhisk/core/controller/test/PackagesApiTests.scala
```
04:41:47  org.apache.openwhisk.core.controller.test.PackagesApiTests > Packages API should not get package reference for a private package in other namespace PASSED
04:41:48  
04:41:48  org.apache.openwhisk.core.controller.test.PackagesApiTests > Packages API should get package with its actions and feeds FAILED
04:41:48      org.scalatest.exceptions.TestFailedException: WhiskPackageWithActions(WhiskPackage/anon-siCgTOzqkjxloE512dgg7MlwuEA/packages_tests_name26@0.0.1,List(WhiskPackageAction(packages_te …
```
> Retry for all PackagesApiTests to stabilize mainBluewhisk

- tests/src/test/scala/org/apache/openwhisk/core/database/test/ReplicatorTests.scala
This code change tries to recover from one of these intermittent failures by retrying the affected testcase.
```
10:10:28  org.apache.openwhisk.core.database.test.ReplicatorTests > Database replication script should replay a database FAILED
10:10:28      org.scalatest.exceptions.TestFailedException: {"offset":0,"rows":[{"doc":{"_id":"_design/snapshotFilters","_rev":"1-9537dd1012a329b18eeee518d0e007d2","filters":{"withoutDeletedAndDesignDocuments":"function(doc, req) {\n    return !doc._deleted && !(doc._id.indexOf(\"_design/\") == 0);\n}"}},"id":"_design/snapshotFilters","key":"_design/snapshotFilters","value":{"rev":"1-9537dd1012a329b18eeee518d0e007d2 …
```
> Retry on failures of replicator replay test

- tests/src/test/scala/org/apache/openwhisk/core/database/test/ReplicatorTests.scala
```
06:58:45  org.apache.openwhisk.core.database.test.ReplicatorTests > Database replication script should continuously update a database STANDARD_OUT
06:58:45      Removing database: continuous_replicatortest_fn-dev-build_database_for_continous_replication
06:58:45      Removing replication doc: continuous_replicatortest_fn-dev-build_database_for_continous_replication
06:58:45      Removing database: replicatortest_fn-dev-build_database_for_continous_replication
06:58:45      Removing database: …
```
> Retry on failures for all ReplicatorTests to stabilize mainBluewhisk

- tests/src/test/scala/org/apache/openwhisk/core/admin/WskAdminTests.scala
```
16:00:56  org.apache.openwhisk.core.admin.WskAdminTests > Wsk Admin CLI should CRD a subject FAILED
16:00:56      org.scalatest.exceptions.TestFailedException: "[Subject id is not recognized]" was not equal to "[subject: anon-9ZekhG3zN61nymgOgxbRUALRXx0
16:00:56      namespace: anon-9ZekhG3zN61nymgOgxbRUALRXx0]"
16:00:56          at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
16:00:56          at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6723) …
```
> Retry on failures for all WskAdminTests to stabilize mainBluewhisk

- tests/src/test/scala/system/basic/WskActivationTests.scala
```
12:48:01  system.basic.WskActivationTests STANDARD_OUT
12:48:01  
12:48:01      Starting test Whisk activations should fetch result using activation result API at 2020-07-03 06:48:01.486
12:48:04  
12:48:04  system.basic.WskActivationTests > Whisk activations should fetch result using activation result API STANDARD_OUT
12:48:04      check failed for activation ce5f191fc93d41e59f191fc93d81e584: {"activationId":"ce5f191fc93d41e59f191fc93d81e584","annotations":[{"key":"path","value":"lime@us.ibm.com/hell …
```
> Retry on failures for all WskActivationTests to stabilize mainBluewhisk

- tests/src/test/scala/org/apache/openwhisk/core/cli/test/ApiGwRestBasicTests.scala
This code change tries to recover from one of these intermittent failures by retrying the failed test. Objective is to stabilize the `mainBluewhisk` builds.
```
21:09:20      Starting test Wsk api should verify get API name that uses custom package at 2020-07-03 15:09:17.702
21:09:20  
21:09:20  org.apache.openwhisk.core.cli.test.ApiGwRestTests > Wsk api should verify get API name that uses custom package STANDARD_OUT
21:09:20      Action invokes within last minute: 28
21:09:20      Action invokes within last minute: 28
21:09:20      Action invokes within last minute: 27
21:09:20  
21:09:20  org.apache.openwhisk.core.cli.test.ApiGwRestTests > Wsk api …
```
> Retry on failure (409) for one test of ApiGwRestBasicTests tests to stabilize mainBluewhisk

- ansible/group_vars/all
> Pin APIGW version to 0.9.10

- tests/src/test/scala/org/apache/openwhisk/core/controller/test/RulesApiTests.scala
This code change tries to recover from one of these intermittent failures by retrying the failed test. Objective is to stabilize the `mainBluewhisk` builds. Test that is retried is: `list rules by default/explicit namespace`
```
20:36:14  org.apache.openwhisk.core.controller.test.RulesApiTests > Rules API should list rules by default/explicit namespace STANDARD_OUT
20:36:14      condition not met, retrying
20:36:14      condition not met, retrying
20:36:14      condition not met, retrying
20:36:15      condition not met, retrying
20:36:15      condition not met, retrying
20:36:15      condition not met, retrying
20:36:15      condition not met, …
```
> Retry on failure for list test of RuleApiTests to stabilize mainBluewhisk

- tests/src/test/scala/org/apache/openwhisk/core/database/test/CouchDbRestClientTests.scala
```
18:00:26  org.apache.openwhisk.core.database.test.CouchDbRestClientTests > CouchDbRestClient should check group Parameter on view-execution FAILED
18:00:26      org.scalatest.exceptions.TestFailedException: 9 did not equal 15
18:00:26          at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
18:00:26          at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6723)
18:00:26          at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6771) …
```
> Retry on failures for all CouchDbRestClientTests tests to stabilize mainBluewhisk

- common/scala/src/main/scala/org/apache/openwhisk/common/TransactionId.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/ActivityEvent.scala
- common/scala/src/main/scala/org/apache/openwhisk/http/ActivityTracker.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/BasicAuthenticationDirective.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActivityTrackerTests.scala
This PR adds enhancements/corrections to the ActivityTracker as detected by the IBM Activity Tracker review.
✅   Green PG build: https://openwhisk-jenkins.swg-devops.com/job/pg1/852/
Summary of changes: 
- `reasonForFailure`is now part of `reason` and it contains the error message of the response (before this PR `reasonForFailure`was just a copy of `reasonType`)
- set the severity based on the operation (delete: critical, update: warning, otherwise: normal) and reasonCode - was hardcoded as `warning` (finding in AT review)
- takes only the first ip from header `x-forwarded-for` as initiator ip address (header may also contain an additional cloudflare-based ip), also addes the addressType for the ip
- message prefix changed from `IBM Cloud Functions:` to `Functions:` (=> finding in AT …
> Enhance ActivityTracker

- common/scala/src/main/scala/org/apache/openwhisk/core/entity/ActivityEvent.scala
- common/scala/src/main/scala/org/apache/openwhisk/http/ActivityTracker.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActivityTrackerTests.scala
Move user-agent to initiator.host.agent
Move the user-agent information from requestData.userAgent to initiator.host.agent as requested by the AT review.
> move field for user-agent to initiator.host.agent

- tests/src/test/scala/system/basic/WskUnicodeTests.scala
```
14:48:11      Starting test ruby:2.5 action should Ensure that UTF-8 in supported in source files, input params, logs, and output results at 2020-07-16 08:48:10.331
14:48:14  
14:48:14  system.basic.WskUnicodeTests > ruby:2.5 action should Ensure that UTF-8 in supported in source files, input params, logs, and output results STANDARD_OUT
14:48:14      check failed for activation 5c5d5fa0364b4f389d5fa0364b3f3830: {"activationId":"5c5d5fa0364b4f389d5fa0364b3f3830","annotations":[{"key":"path","value":"l …
```
> Retry on failures for all WskUnicodeTests tests to stabilize mainBluewhisk

- tests/src/test/scala/system/basic/WskMultiRuntimeTests.scala
```
system.basic.WskMultiRuntimeTests STANDARD_OUT
Starting test should update an action with different language and check preserving params at 2020-07-16 17:38:32.240
system.basic.WskMultiRuntimeTests > should update an action with different language and check preserving params STANDARD_OUT
Exception occurred during test execution: org.scalatest.exceptions.TestFailedException: error waiting for activation …
```
> Retry on failures for all WskMultiRuntimeTests tests to stabilize mainBluewhisk and health test for production deployments

- tests/src/test/scala/system/basic/WskPackageTests.scala
```
system.basic.WskPackageTests STANDARD_OUT
Finished test Wsk Package should contain an binding annotation if invoked action is in the package binding at 2020-07-16 18:07:09.389
Starting test Wsk Package should not contain an binding annotation if invoked action is not in the package binding at 2020-07-16 18:07:09.389
system.basic.WskPackageTests > Wsk Package should not contain an binding annotation if invoked action is not in …
```
> Retry on failures for all WskPackageTests tests to stabilize mainBluewhisk and health test for production deployments

- tests/src/test/scala/common/WskTestHelpers.scala
This code change tries to recover from one of these intermittent failures by retrying the failed test. Objective is to stabilize the `mainBluewhisk` builds.
The PR does retries in the AssetCleaner logic for 409 errors for all asset types/operations.
```
system.basic.WskRestBasicTests > Wsk Trigger REST should create and fire a trigger with a rule whose action has been deleted STANDARD_OUT
ERROR: deleting asset failed for t1tor1r2-1594924982133: org.scalatest.exceptions.TestFailedException: HTTP request or response did not match the Swagger spec.
Request: HttpRequest(HttpMethod(DELETE),https://fn-prod-fra-01.eu-de.containers.appdomain.cloud/api/v1/names …
```
> Do retries in AssetCleaner on 409 for all deletion operations

- tools/ow-utils/Dockerfile
fix ow-utils image build issue
https://github.com/apache/openwhisk/issues/4936
- [x ] General tooling
> fix ow-utils image build issue

- common/scala/Dockerfile
upgrade alpine base image to address vulnerabilities
bluewhisk/issues/9611
> upgrade alpine base image

- common/scala/src/main/scala/org/apache/openwhisk/core/entity/BasicAuthenticationAuthKey.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/Identity.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/Secret.scala
- common/scala/src/main/scala/org/apache/openwhisk/utils/CryptHelpers.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/SchemaTests.scala
Helper methods to encrypt plain text to and decrypt from AES encrypted string.
This code change/PR is to address the requirement for storing access keys as encrypted data.
> Encrypt/decrypt EK

- .travis.yml
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/InvokerSupervision.scala
- tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
- tools/travis/scan.sh
Log a summary message showing the number of healthy/unhealthy invokers
Log an additional message showing the number of invokers with states `Healthy`, `Unhealthy`, `Unresponsive` and `Offline`.
> Log a summary message showing the number of healthy/unhealthy invokers

- settings.gradle
> Update akka-http to 10.1.14

- tests/src/test/scala/org/apache/openwhisk/core/database/s3/CloudFrontSignerTests.scala
```
[2021-03-24T02:03:24.258Z] org.apache.openwhisk.core.database.s3.CloudFrontSignerTests > CloudFront config should generate a signed url FAILED
[2021-03-24T02:03:24.258Z]     org.scalatest.exceptions.TestFailedException: Some("1616552004") was not equal to Some("1616552003")
[2021-03-24T02:03:24.258Z]         at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
[2021-03-24T02:03:24.258Z]         at …
```
> Retries on testcase failures (cont.)

- core/controller/src/main/scala/org/apache/openwhisk/core/controller/RestAPIs.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/RespondWithHeadersTests.scala
- tests/src/test/scala/services/HeadersTests.scala
1. Removing CORS `Access-Control-Allow-Origin: *` header from RestApi
2. Adding some securing headers to RestApi
**For 1**
- Dynamic App Scan complains about Cloud Functions RestApi CORS header `Access-Control-Allow-Origin: *` being set overly permissive, requesting to either return a list of allowed sites or to drop it.
- For a cloud offering, it is hardly feasible to maintain whitelisting for potentially many 3rd party users' origins.
- A RestApi is not necessarily the prime target for CORS (in contrast to a web application).
- Thus decided to drop ACAO header which means `same-origin` policy.
- Impact to end-users cannot be estimated as we don't know their usage/integration pattern of our RestApi.
- The change does not impact WebActions, only the RestAPI. (For WebActions, developers …
> RestApi headers change (no CORS ACAO, add some securing ones)

- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/InvokerSupervision.scala
> Add isBlacklisted flag to ping message (cont.)

- .travis.yml
Exclude standalone tests from being executed in Travis
> Exclude standalone tests from being executed in Travis

- common/scala/Dockerfile
upgrade version of jdk/alpine image (base image of scala image)
upgrade version of jdk/alpine image (base image of scala image) to adreess vulnerability issue
from
adoptopenjdk/openjdk8-openj9:x86_64-alpine-jdk8u262-b10_openj9-0.21.0
to 
adoptopenjdk/openjdk8-openj9:x86_64-alpine-jdk8u312-b07_openj9-0.29.0
> jdk alpine version upgrade

- build.gradle
- core/monitoring/user-events/src/test/scala/org/apache/openwhisk/core/monitoring/metrics/ApiTests.scala
- settings.gradle
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ControllerTestCommon.scala
- tools/travis/setup.sh
Upgrade to Akka HTTP 10.2.7 which is an important security fix release.
> Upgrade to Akka HTTP 10.2.7

- common/scala/Dockerfile
upgrade version of jdk/alpine image (base image of scala image)
upgrade version of jdk/alpine image (base image of scala image) to adress vulnerability issue
from
adoptopenjdk/openjdk8-openj9:x86_64-alpine-jdk8u312-b07_openj9-0.29.0
to adoptopenjdk/openjdk8-openj9:x86_64-alpine-jdk8u322-b06_openj9-0.30.0
- ✔️ PG6 build 628 passed successfully
> Update java 8 to level 322.

- common/scala/Dockerfile
updating `adoptopenjdk/openjdk8-openj9:x86_64-alpine-jdk8u322-b06_openj9-0.30.0` to `adoptopenjdk/openjdk8-openj9:x86_64-alpine-jdk8u332-b09_openj9-0.32.0` to fix vulnerabilities
> Update Base image to fix vulnerabilities

- tests/src/test/scala/org/apache/openwhisk/core/entity/test/SchemaTests.scala
> Add node 16 testcase

- common/scala/src/main/scala/org/apache/openwhisk/utils/Retry.scala
- tests/src/test/scala/common/WskCliOperations.scala
- tests/src/test/scala/common/rest/WskRestOperations.scala
Consider null msg value in Throwable.
> [Scala tests] Redact EK (cont.)

- settings.gradle
- tools/travis/distDocker.sh
Exclude standalone build from travis
> Exclude standalone tests from being executed in Travis (cont.)

- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
Check the file system disk space usage to avoid that invokers run out of space.
Invoker pods may run out of space on their root and log volumes for very frequent scheduled actions producing a high load of log messages or because of many docker images which are not cleaned up. By this code change this situation is taken into consideration and the affected invoker will be temporary evacuated until the situation relaxes. Now also the maximum file occupation level is adapted (lowered or increased) to avoid flipping invoker states.
> Check the file system disk space usage to avoid that invokers run out of space (cont.)

- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Actions.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Packages.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Rules.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Triggers.scala
Validate PUT playload for unexpected fields to reject with `400 Bad Request` for Action/Package/Trigger/Rule create/update requests.
> Validate PUT payload for unexpected fields 

- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Actions.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Packages.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Rules.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Triggers.scala
Validate PUT playload for unexpected fields and log accordingly..
> Validate PUT payload for unexpected fields (cont.)

- common/scala/Dockerfile
Old: open-8u332-b09-jdk-focal
New: open-8u345-b01-jdk-focal
Update used base image for security fix
PG was Successful : pg1 2264
- [ x ] Controller
- [ x ] Invoker
> Update Scala base Image

- tests/dat/actions/unicode.tests/go-1.19.txt
- tests/dat/actions/unicode.tests/php-8.1.txt
Add Unicode tests for php and go
> Add missing test cases for go and php

- tests/src/test/scala/actionContainers/BasicActionRunnerTests.scala
> Support backward compatibility for runtime's return type

- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/ImageMonitor.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
Record all invoked docker images and related actions and put them in store.
Record all invoked docker images and related actions and put them in store.
> Image monitor

- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/ImageMonitor.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
Record all invoked docker images and related actions and put them in store. Make sure the couchdb view is updated accordingly.
Record all invoked docker images and related actions and put them in store.
> Image monitor (cont.)

- .github/workflows/run-tests.yml
> Github action to run tests that travis did

- common/scala/Dockerfile
> upadate Scala base image

- ansible/README.md
- tools/macos/README.md
- tools/macos/docker-machine/README.md
- tools/ow-utils/Dockerfile
- tools/travis/setup.sh
- tools/ubuntu-setup/ansible.sh
Update to ansible==2.8.18.
- Required to support build on ubuntu/focus environments.
- Required to run with python 3.9+.
- none
> Update to ansible==2.8.18.

- .github/workflows/run-tests.yml
Run the system tests to verify pull requests.
Run the system tests to verify pull requests. Was previously done in the .travis.yml.
- Use java 8 in the github actions.
- Set a default ANSIBLE_CMD for all github actions steps.
- Run the system tests to verify the changes of a pull request.
> Run the system tests to verify pull requests.

- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
Log activation when read from Kafka. In addition log action document revision when read from Cloudant.
Log activation when read from Kafka and action document revision when read from Cloudant with `warn` log level.
> Log activation when read from Kafka (cont.)

- common/scala/Dockerfile
- tools/ow-utils/Dockerfile
> update semeru base image to open-8u362-b09-jdk-focal

- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
Log once every 10th minute that controller metrics were emitted.
The additional log message allows to check if the scheduler task (`actorSystem.scheduler.schedule`) which schedules the `emitMetrics` method every 10 seconds is still running in the controller pods/containers.
> Log once every 10th minute that controller metrics were emitted

- .github/workflows/run-tests.yml
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
- The code formatting was tested as part of the unit tests. As this test is actually not done for PRs, code formatting errors are not found. Added this to the github action to be checked for PRs.
> Check code formatting for PRs.

- common/scala/Dockerfile
- tools/ow-utils/Dockerfile
> update scala base image to open-8u372-b07-jdk-focal

- tests/dat/actions/unicode.tests/go-1.21.txt
- tests/dat/actions/unicode.tests/nodejs-16.txt
- tests/dat/actions/unicode.tests/nodejs-20.txt
> add unicode tests for go 1.21, node 16 and 20

- common/scala/Dockerfile
- tools/ow-utils/Dockerfile
> Update jdk parent image to tag 'open-8u412-b08-jre-focal'

- common/scala/Dockerfile
- tools/ow-utils/Dockerfile
> update openjdk tag to open-8u422-b05-jdk-focal
